# Custom Language File for Launcher Customizer

[ejs.app]
title = "Rise of Shinobi Launcher"

[ejs.landing]
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/x7ujeNUUZS"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR RISE OF SHINOBI"
welcomeDescription = "Rise of Shinobi est un serveur Minecraft roleplay inspiré de l’univers de Naruto.Entièrement pensé pour l’immersion, il propose un monde vivant, évolutif, où chaque joueur peut s’intégrer à une expérience narrative riche. Ici, vous incarnez un shinobi au sein d’un village, vous progressez, vous interagissez, vous vous faites une place. L’univers est conçu pour que chaque action compte : rien n’est figé, tout peut évoluer selon les décisions collectives comme individuelles. Explorez, entraînez-vous, tissez des liens, participez à des intrigues profondes, ou observez le monde se transformer autour de vous. Que vous soyez là pour vivre une aventure, progresser dans un système de jeu complet, ou simplement découvrir un monde unique, Rise of Shinobi est un univers évolutif où chaque joueur écrit une histoire qui compte, jour après jour."
welcomeDescCTA = "Vous n'êtes qu'à quelques clics de devenir le plus grand des ninjas."
