[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essentiels"
newsButton = "ACTUALITÉS"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter..."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Vérification des actualités..."
newsErrorFailedSpan = "Échec du chargement des actualités"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune actualité"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "EMAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d’un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et n’est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n’est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Se connecter avec Microsoft"
loginWithMojang = "Se connecter avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Lanceur"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajouter ou gérer des comptes existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Connexion automatique au serveur au lancement."
launchDetachedTitle = "Lancer le jeu séparément du lanceur."
launchDetachedDesc = "Si le jeu n’est pas lancé séparément, fermer le lanceur fermera aussi le jeu."

tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Activer ou désactiver les mods."
switchServerButton = "Changer"
requiredMods = "Mods requis"
optionalMods = "Mods optionnels"
dropinMods = "Mods à insérer"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Packs de shaders"
shaderpackDesc = "Activer ou désactiver les shaders. Attention, les shaders ne fonctionnent correctement que sur des configurations puissantes. Vous pouvez ajouter des packs personnalisés ici."
selectShaderpack = "Sélectionner un pack de shaders"

tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Configurer Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM maximale"
minRAM = "RAM minimale"
memoryDesc = "La RAM minimale recommandée est de 3 Go. Fixer les valeurs min et max identiques peut réduire les lags."
memoryTotalTitle = "Totale"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner l’exécutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L’exécutable Java est vérifié avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options à passer à la JVM à l’exécution. <em>-Xms</em> et <em>-Xmx</em> ne doivent pas être inclus."

launcherTabHeaderText = "Paramètres du lanceur"
launcherTabHeaderDesc = "Options liées au lanceur."
allowPrereleaseTitle = "Autoriser les mises à jour préliminaires."
allowPrereleaseDesc = "Les préversions incluent des fonctionnalités pouvant ne pas être totalement testées ou intégrées.<br>Ceci sera toujours vrai si vous utilisez une version préliminaire."
dataDirectoryTitle = "Dossier des données"
selectDataDirectory = "Sélectionner le dossier des données"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et installations Java locales seront stockés dans ce dossier.<br>Les captures d’écran et sauvegardes se trouvent dans le dossier d’instance du serveur concerné."

aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Afficher les informations et notes de version de cette version."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "Console DevTools"
releaseNotes = "Notes de version"
changelog = "Journal des modifications"
noReleaseNotes = "Aucune note de version"
viewReleaseNotes = "Voir les notes de version sur GitHub"

launcherUpdatesHeaderText = "Mises à jour du lanceur"
launcherUpdatesHeaderDesc = "Télécharger, installer et consulter les mises à jour du lanceur."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Nouveautés"
updateReleaseNotes = "Notes de mise à jour"

[ejs.waiting]
waitingText = "En attente de Microsoft..."

[ejs.welcome]
continueButton = "CONTINUER"

[js.discord]
waiting = "En attente du client..."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION EN COURS"
success = "RÉUSSI"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue est survenue. Veuillez consulter la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter..."
failureTitle = "Erreur lors du lancement"
failureText = "Voir la console (CTRL + Maj + i) pour plus de détails."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement..."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Analyse des infos système..."
noCompatibleJava = "Aucune installation<br>Java compatible trouvée"
installJavaMessage = "Pour lancer Minecraft, vous avez besoin d'une installation Java 64 bits {major}. Voulez-vous qu’on l’installe pour vous ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement de Java..."
javaDownloadFailureTitle = "Erreur lors du téléchargement de Java"
javaDownloadFailureText = "Voir la console (CTRL + Maj + i) pour plus de détails."
javaRequired = "Java est requis<br>pour lancer"
javaRequiredMessage = "Une installation valide de Java {major} en 64 bits est requise pour lancer le jeu.<br><br>Veuillez consulter notre <a href=\"https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java\">guide de gestion Java</a> pour les instructions d'installation manuelle."
javaRequiredDismiss = "Je comprends"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Impossible de trouver une distribution OpenJDK."
javaDownloadCorruptedError = "Le JDK téléchargé est corrompu (empreinte incorrecte)."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des informations serveur..."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger l’index de distribution. Voir la console (CTRL + Maj + i) pour plus de détails."
pleaseWait = "Veuillez patienter..."
errorDuringLaunchTitle = "Erreur lors du lancement"
seeConsoleForDetails = "Voir la console (CTRL + Maj + i) pour plus de détails."
validatingFileIntegrity = "Validation de l'intégrité des fichiers..."
errorDuringFileVerificationTitle = "Erreur lors de la vérification des fichiers"
downloadingFiles = "Téléchargement des fichiers..."
errorDuringFileDownloadTitle = "Erreur lors du téléchargement des fichiers"
preparingToLaunch = "Préparation au lancement..."
launchingGame = "Lancement du jeu..."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, n’a pas pu être téléchargé correctement. Le jeu ne peut donc pas se lancer.<br><br>Pour corriger ce problème, désactivez temporairement votre antivirus et relancez le jeu.<br><br>Si vous avez le temps, merci de <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">signaler un problème</a> en nous indiquant l'antivirus utilisé."
doneEnjoyServer = "Terminé. Bon jeu !"
checkConsoleForDetails = "Veuillez consulter la console (CTRL + Maj + i) pour plus de détails."

[js.landing.news]
checking = "Vérification des actualités"

[js.landing.discord]
loading = "Chargement du jeu..."
joining = "En route vers Westeros !"
joined = "Exploration du royaume !"

[js.overlay]
dismiss = "Fermer"

